language: objective_c
osx_image: xcode8
env:
  - XCODEBUILD_PLATFORM='iOS Simulator' XCODEBUILD_SIM_OS=10.3.1 XCODEBUILD_DEVICE='iPhone 6' XCODEBUILD_ACTION=build
xcode_project: "Sample iOS.xcodeproj"
install:
  - xcodebuild -project "Sample iOS.xcodeproj" -scheme "Sample iOS" -sdk "iphonesimulator10.3" clean analyze
  - xcodebuild -project "Sample iOS.xcodeproj" -scheme "Sample iOS" -archivePath "$PWD/SampleiOS.xcarchive" archive
  - xcodebuild -exportArchive -archivePath "$PWD/SampleiOS.xcarchive" -exportPath -exportOptionsPlist "$PWD/Sample iOS/Info.plist"
