language: objective-c
xcode_scheme: "Sample iOS"
xcode_project: "Sample iOS.xcodeproj"
install:
  - xcodebuild -project "Sample iOS.xcodeproj" -scheme "Sample iOS" -sdk "/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk" clean analyze
  - xcodebuild -project "Sample iOS.xcodeproj" -scheme "Sample iOS" -archivePath "$PWD/SampleiOS.xcarchive" archive
  - xcodebuild -exportArchive -archivePath "$PWD/SampleiOS.xcarchive" -exportPath -exportOptionsPlist "$PWD/Sample iOS/Info.plist"
